name: monad-cli
version: 0.1.0.0
github: "AlamarW/monad-cli"
license: BSD3
author: "Your Name"
maintainer: "your.email@example.com"
copyright: "2025 Your Name"

extra-source-files:
- README.md
- CLAUDE.md

synopsis: A composable CLI toolkit using monadic transformations
category: CLI

description: |
  monad-cli reimagines basic command line tools using Haskell's type system
  and monadic composition to enable seamless command composition without
  interface adapters like xargs.

dependencies:
- base >= 4.7 && < 5
- text
- containers
- streaming
- filepath
- directory
- bytestring

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
  - Core.Types
  - Commands.Find
  - Commands.Ls
  - Commands.Grep
  - Commands.Cat
  - Parser.Pipeline
  - Runtime.Executor

executables:
  monad-cli:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - monad-cli

tests:
  monad-cli-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - monad-cli
    - hspec
    - QuickCheck
