# Resolver - specifies the GHC version and package set
# LTS 22.x uses GHC 9.6.x which is the recommended version
resolver: lts-22.42

# Packages to be built (local packages)
packages:
- .

# Extra dependencies not in the resolver
extra-deps: []

# Override default flag values for local packages
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true

# Require a specific version of Stack
# require-stack-version: -any # Default
# require-stack-version: ">=2.15"

# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64

# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]

# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
